import Link from "next/link";
export default function Home(){
 const ticker="CHIKKAMAGALUR • KODAGU • PLANTATION AA • MONSOONED MALABAR • ROBUSTA PARCHMENT • ";
 return <main id="main">
  <section className="hero"><img src="/images/origin.jpg" alt="Coffee plantation in the Western Ghats"/><div className="hero-content"><p className="kicker">Rihla Global · Bengaluru, India</p><h1><span className="line-mask"><span>Indian green coffee,</span></span><span className="line-mask"><span>prepared for the world.</span></span></h1><p className="lede">Export-ready Arabica, Robusta, and specialty grades with clear physical specifications, considered packing, and a responsive export desk.</p><div className="actions"><Link className="button light" href="/products">Explore coffees <span>↗</span></Link><Link className="button ghost" href="/contact">Request specifications <span>→</span></Link></div></div></section>
  <div className="marquee"><div className="marquee-track">{ticker.repeat(4)}</div></div>
  <section className="section"><div className="section-head reveal"><span className="section-no">01 / ORIGIN</span><h2>A supply story with a clear point of view.</h2></div><div className="supply"><div className="sticky"><p className="kicker">From India to your programme</p><p className="prose">We focus on the practical details behind a dependable lot: origin, preparation, physicals, packing, and documents.</p></div><div>{[["Plantation","Relationships across major Indian coffee-producing regions."],["Cherry & Process","Washed, natural, and monsooned preparations aligned to the required grade."],["Green Coffee","Screen, moisture, and defect information shared before confirmation."],["Export Desk","Direct coordination from enquiry and sampling through documents and dispatch."]].map(([t,p],i)=><article className="story-step reveal" key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{p}</p></div></article>)}</div></div></section>
  <section className="stats"><div className="stat"><strong>500 kg</strong><span>Minimum order</span></div><div className="stat"><strong>60 kg</strong><span>Standard jute bags</span></div><div className="stat"><strong>On request</strong><span>GrainPro / hermetic liners</span></div></section>
  <section className="section"><div className="section-head reveal"><span className="section-no">03 / GRADES</span><h2>Three expressions of Indian green coffee.</h2></div><div className="card-grid">{[["arabica","Arabica","Washed plantation grades with elegant structure.","/images/arabica-grade.jpg"],["robusta","Robusta","Washed and natural grades built for strength and body.","/images/robusta-grade.jpg"],["specialty","Specialty","Distinctive preparations with unmistakable Indian character.","/images/specialty-monsoon.jpg"]].map(([s,t,p,image],i)=><Link className="coffee-card reveal" href={`/products/${s}`} key={s}><img src={image} alt={`${t} green coffee`}/><div className="card-copy"><span className="kicker">0{i+1} / Coffee</span><h3>{t}</h3><p>{p}</p></div></Link>)}</div><div className="actions"><Link className="button dark" href="/products">View all products <span>↗</span></Link></div></section>
  <section className="section cta-band"><div><p className="kicker">04 / Export desk</p><h2 className="editorial-title">Start with the specification your programme needs.</h2></div><div className="actions"><Link className="button light" href="/contact">Request specifications <span>↗</span></Link><a className="button ghost" href="https://api.whatsapp.com/send?phone=919398540256" target="_blank" rel="noopener noreferrer">WhatsApp <span>↗</span></a></div></section>
 </main>
}